### ISSUE TITLE
Feedback during error

### ISSUE THREAD

**Issue by jeroenleenarts** [rufo/instafari#1]
Hey Rufo,

Looked at your Instapaper extension. Got some nice ideas I didn't come up with yet.

There's one thing though, I can see that you are using console msgs to output error details. But it seems there is no way to get to the console in any way.

Might it be an idea to pop an alert instead of only blinking the "thumb down" icon? It would be helpfull to be able to report to the user wether either a 403 or 500 error occured. (In a more user friendly language ofcourse.)

Kind regards,
Jeroen

(I think I'm going to nuke my Instapaper add-on tonight. I like yours more.)

**Comment by rufo** [comment]
The error handling is _definitely_ too bare-bones at the moment. :-)

The console information is really only viewable if you have the extension loaded through the Builder (under the Global Page section). An alert might be an improvement (honestly, for some reason I hadn't thought alert() would work in the global page), but I was thinking an extension bar might be nicer and less obtrusive. I'm not sure it'll work the way I have in mind, though.

If I get a chance, I'll hack on this later today.

(edited to remove horrendous run-on sentence)

**Comment by jeroenleenarts** [comment]
For your consideration:
http://github.com/jeroenleenarts/instafari/commit/81bdf98984c63c28c39e00f759395ff2fba4bf7b

(Hoping a commit link will work.)

I've made some minor modifications on my branch of your codebase.

**Comment by rufo** [comment]
Added in 0.2 - thanks Jeroen!
