### ISSUE TITLE
Submit Safari Extension to Apple

### ISSUE THREAD

**Issue by jeroenleenarts** [rufo/instafari#4]
From what I understand the signer of the extension needs to submit the extension to Apple for inclusion in the Safari Extension galary.
https://developer.apple.com/submission/safari/

What's the plan with Instafari? Are we submitting as well?

**Comment by rufo** [comment]
I'll probably submit, though I'd like to get at least a 0.3 release together. Hopefully this week, though I've been busy as hell with my paid projects.

**Comment by jeroenleenarts** [comment]
I've created a patch on my fork which implements the 0.3 features on the current roadmap. I've been running my own build and sofar it seems stable. Only thing I noticed that I initially had some strange error in my code. It resolved itself by manually refreshing a page and since hasn't appeared again.

If the code checks out on your end, I'd say we go for it.

I do wonder when the official Instapaper Extension will arrive.
